// Generate Button
const btn = document.querySelector('#generate-btn');

// Array with all of the startup/tech companies
const startupArray = [
    'YouTube',
    'Facebook',
    'Instagram',
    'LinkedIn',
    'Twitter',
    'Shazam',
    'Photoshop',
    'Illustrator',
    'After Effects',
    'Reddit',
    'Netflix',
    'Udemy',
    'Rotten Tomatoes',
    'GitHub',
    'GitKraken',
    'IMDb',
    'Flickr',
    'Gmail',
    'Stack Overflow',
    'Wikipedia',
    'Behance',
    'Expedia',
    'Docker',
    'eBay',
    'Audible',
    'Bandcamp',
    'Dropbox',
    'Dribble',
    'Tinder',
    'Snapchat',
    'Grindr',
    'Discord',
    'Slack',
    'Clio',
    'Plenty of Fish',
    'Amazon',
    'Pinterest',
    'Indeed',
    'Spotify',
    'TikTok',
    'Skip the Dishses',
    'Uber Eats',
    'DoorDash',
    'Uber',
    'Lyft',
    'SiriusXM',
    'Airbnb',
    'Duolingo',
    'Squarespace',
    'Craigslist',
    'Meetup',
    'Pirate Bay',
    'Steam',
    'WhatsApp',
    'Etsy',
    'Evernote',
    'Hootsuite',
    'Tumblr',
    'Trip Advisor',
    'Twitch',
    'Vimeo',
    'Twitch',
    'Blogger',
    'Medium',
    'Linux',
    'iTunes',
    'Excel',
    'Soundcloud',
    'CodePen',
    'Skype',
    'Amazon'
];

// Array with all of the possible options/'but it's for...'
const optionArray = [
    'dogs',
    'food',
    'lazy people',
    'pizza',
    'people with palms that are sweaty, week knees, and heavy arms',
    'people who use the dark web',
    'doctors',
    'cars',
    'pigeons',
    'Tom Cruise',
    'people who swear way to fucking goddamn much',
    'pilots',
    'chefs',
    'people who nevr make spelling mistakes',
    'cats',
    'trains',
    'cashiers',
    'trailer trash',
    'morons',
    'YouTubers experiencing burnout',
    'memes',
    'rich people who need more things',
    'influencers',
    'that guy in his garage with his Lamborghini',
    'people who never shut the fuck up',
    'dead memes',
    'bad drivers',
    'the deadweights of society',
    'drug dealers',
    'pharmacist',
    'pissing off your annoying neighbour',
    'hikers',
    'people who just do not give a single fuck',
    'cows',
    'birds',
    'zombies',
    'some seriously kinky shit',
    'people who like dad jokes too much',
    'metalheads',
    'K-pop fans',
    'people are high, like, all the time',
    'cosplayers',
    'front end developers',
    'back end developers',
    'full stack developers',
    'actors',
    'dat boi',
    'collectors',
    'dancers',
    'directors',
    'lobsters',
    'deciding which wine and cheese pair to have after sex',
    'swimmers',
    'photographers',
    'Canadians who are not nice',
    'hoarders',
    'programmers',
    'people posting a screenshot of this to r/ProgrammerHumor',
    'gamers',
    'people who dab unironically',
    'Xbox fanboys',
    'PlayStation fanboys',
    'adults who still like Pokemon',
    'those 3 guys who still like Yu-Gi-Oh',
    'Magic: The Gathering players',
    'people who like the MCU waaayyy too much',
    '10x engineers',
    'people who use memes irl, smh',
    'things that are definitely illegal'
];

// Generate 
btn.addEventListener('click', e => {
    e.preventDefault();

    // Generate random startup/tech company value
    const randomComp = startupArray[Math.floor(Math.random() * startupArray.length)];

    // Generate random options/'but it's for...' value
    const randomOption = optionArray[Math.floor(Math.random() * optionArray.length)];

    // Inject a response into the empty paragraph
    document.querySelector('#generated-text').innerHTML = `"Well, it's like ${randomComp}, but for ${randomOption}."`;
});